site_name: Authentication Manager Configuration for Fast Connect Use Cases for Citrix Workspace app for Linux
site_description: Authentication Manager Configuration for Fast Connect Use Cases for Citrix Workspace app for Linux
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/workspace-linux-authentication-manager-configuration/issues/new
assignees_uri:
  - ajitchelat
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'

# Page tree
nav:
- Home: index.md
